http:
  routers:
    host:
      entryPoints:
        - http
      service: service-host
      rule: Host(`localhost`)
  services:
    service-host:
      loadBalancer:
        servers:
          - url: http://ch1:8123
          - url: http://ch2:8123
        passHostHeader: true
        healthCheck:
         path: /
         interval: "5s"
         timeout: "5s"
